title: "Zen | Blogspot Template Creator | Web Dev | Android Dev | 081545143654"

permalink: /:year/:month/:day/:title/

paginate: 10

plugins:
  - jekyll-paginate
  - jekyll-feed
  
name: Zen
description: Developer
url: http://blog2.muhammadzaini.com