# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Zen
email: muhzaini30@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Seorang developer.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://blog2.muhammadzaini.com" # the base hostname & protocol for your site
twitter_username: mzaini30
github_username:  mzaini30

# Build settings
markdown: kramdown

# lokasi blog di linux
lokasi: '/media/zen/data/web/blog (github)/'